// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeggieFarmer.Server.Data;

#nullable disable

namespace VeggieFarmer.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230222123743_CreateInitial")]
    partial class CreateInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeggieFarmer.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tomato is a juicy berry used in cooking, high in vitamins and minerals.",
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/330px-Tomato_je.jpg",
                            Price = 9.99m,
                            Title = "Tomato"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cucumber is a green, refreshing vegetable, low in calories and high in vitamins and minerals.",
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/800px-ARS_cucumber.jpg",
                            Price = 5.99m,
                            Title = "Cucumber"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Carrot is an orange root vegetable, sweet and crunchy, high in vitamins and minerals.",
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/1024px-Vegetable-Carrot-Bundle-wStalks.jpg",
                            Price = 2.99m,
                            Title = "Carrot"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Radish is a crunchy, spicy root vegetable, low in calories and high in vitamins and minerals.",
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Radish_3371103037_4ab07db0bf_o.jpg/800px-Radish_3371103037_4ab07db0bf_o.jpg",
                            Price = 12.99m,
                            Title = "Radish"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Turnip is a root vegetable with a slightly sweet and earthy flavor.",
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/d/d3/Turnip_2622027.jpg",
                            Price = 3.99m,
                            Title = "Turnip"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
